### ISSUE TITLE
Have you tried vnStat?

### ISSUE THREAD

**Issue by emnoor** [dufferzafar/netuse#2]
> [...] I couldn't find anything similar for Linux [...]

Try [vnStat](http://humdi.net/vnstat/), it does exactly what you are trying to do. Just putting it here to let you know. :-)

BTW, there's isn't anything that notifies for usage of a specific data volume. Good luck with those features. :+1:

**Comment by dufferzafar** [comment]
I do remember using vnStat, but tbh don't remember what issues i found with it. 

Will give it another shot, I guess - even if just to find some cool features that I could then implement in netuse.

> BTW, there's isn't anything that notifies for usage of a specific data volume

Can you please elaborate a bit?
