### ISSUE TITLE
Monitor activities using most of the data.

### ISSUE THREAD

**Issue by iCHAIT** [dufferzafar/netuse#8]
This may go as a feature request but how about being able to figure out which activities consumes most of my data.

We can have a weekly or daily overview of the amount of data spent on different activities.

Essentially the output of the `-w` switch plus the breakup of the data, spent on different activities for that particular week as a whole or even have a day wise overview.

Thoughts??

**Comment by iCHAIT** [comment]
BTW, I was just searching something similar for OS X and [found this](https://github.com/codebox/bitmeteros), the GUI looks neat and the CLI for the app also seems to be reasonable, worth taking a look.

Thoughts on this?

**Comment by dufferzafar** [comment]
I remember BitMeter OS at some point of time, but it didn't work out for me well.

Also, about your original feature request, currently we don't track which application is consuming the data. We only know how much is being transferred (upload/download.) 

Though, having per application download statistics would be immensely valuable, I know of no way to do that. If someone else does, feel free to hit up a PR.

Closing this for lack for direction.
